### PR TITLE
Add support for pod topologySpreadConstraints in deployment spec

### PR DESCRIPTION
**Pull request by sergeyshevch**
#### Overview

Added support for pod topologySpreadConstraints in deployment spec

#### What this PR does / why we need it

We use topologySpreadConstraints as a better alternative for podAnityAffinity. Also some projects as https://github.com/aws/karpenter currently doesn't support podAnityAffinity

#### Checklist

- [x] Change log updated in `Chart.yaml` (see the contributing guide for details)
- [x] Chart version bumped in `Chart.yaml` (see the contributing guide for details)
- [X] Documentation regenerated by running `make docs`

### CODE REVIEW

**Comment by sergeyshevch** [comment]
@sagikazarmark I guess this is ready for review. It's really small changes for introduce topologySpreadConstraints in this chart

**Comment by sergeyshevch** [comment]
@sagikazarmark @nabokihms Can you look on it?

**Comment by sagikazarmark** [comment]
@sergeyshevch I wonder if it makes sense to let the user fill in the pod label selector. Since pods are created from a deployment template, every label you want to match would match all pods. We can easily do that for the user from the template.

WDYT @sergeyshevch @nabokihms ?

**Comment by sergeyshevch** [comment]
@sagikazarmark It's possible, but it's a not common way to do it in charts IMO. So If we add labels for topologySpreadConstraints then we also need to add it for example for podAntiAffinity. 

Currently, users can specify those conditions by himself

**Comment by sagikazarmark** [comment]
@sergeyshevch Hm, indeed.

Well, one last ask then before merging: please rebase/force push your last commit to trigger the CI again.

**Comment by sergeyshevch** [comment]
@sagikazarmark Ok thanks! I will do it today

**Comment by sergeyshevch** [comment]
@sagikazarmark This branch already rebased on top of master so i cannot trigger force-push on it. As I see, you can trigger CI manually

**Comment by sagikazarmark** [comment]
I can't (or don't know how). Just do a `git commit --amend` and then `git push --force-with-lease`.

**Comment by sergeyshevch** [comment]
Yeah sure. I forgot about amend usage for such purpose

**Review by sagikazarmark — APPROVED** [review]

**Comment by sagikazarmark** [comment]
Thanks @sergeyshevch

**Pull request merged**
