### PR TITLE
Add support for extra secrets

### PR DESCRIPTION
**Pull request by jkroepke**
#### What this PR does / why we need it

It gives the ability to define extra credentials.

Use case: I want to pass sensitive credentials trough kubernetes secrets and pass them as environment variable.

#### Checklist

- [ ] Change log updated in `Chart.yaml` (see the contributing guide for details)
- [ ] Chart version bumped in `Chart.yaml` (see the contributing guide for details)
- [ ] Documentation regenerated by running `make docs`

### CODE REVIEW

**Comment by sagikazarmark** [comment]
@jkroepke I believe you could already achieve the same using `envVars` or `envFrom`. Can you please check if those fit your use case? Thanks!

**Comment by jkroepke** [comment]
Hi @sagikazarmark 

it does not fit our case, since it required an external secret. And if there are changes on that external secret, no new deployment is triggerd. That would be the use case.

On Top, if I want to deployment dex with ArgoCD, I have to create a dedicated ArgoCD App only for the additional secret. With this PR, everything can be bundled in one deployment.

**Comment by sagikazarmark** [comment]
I see. Let me think about this. I'm not particularly fond of this solution TBH.

As for ArgoCD: what I've done in the past is wrapping charts to add additional secrets. That pattern worked quite well as a means to extend charts.

**Comment by jkroepke** [comment]
> That pattern worked quite well as a means to extend charts.

I agree.

But I general, I much appreciate it, if the upstream helm charts directly supports passing sensitive environment variables.

See other examples:
- https://github.com/grafana/helm-charts/blob/3228d102b5ebff3da462579efe9beca84bb15270/charts/grafana/values.yaml#L413-L415


Passing sensitive environment variables is quite common for dex, since the dex config supports environment variables for client secrets, client ids...

**Comment by jkroepke** [comment]
@sagikazarmark can we proceed here?

**Pull request closed without merging**
