### PR TITLE
fix: add missing defaults on servicemonitor

### PR DESCRIPTION
**Pull request by bendikp**
#### Overview

Add missing default values on ServiceMonitor.

#### What this PR does / why we need it

In https://github.com/dexidp/helm-charts/pull/105 two new values, `.Values.serviceMonitor.honorLabels` and `.Values.serviceMonitor.path`, was introduced without any default values. If these values are not set by the user the value become `null` and installation in a k8s cluster fails. 

#### Checklist

- [x] Change log updated in `Chart.yaml` (see the contributing guide for details)
- [x] Chart version bumped in `Chart.yaml` (see the contributing guide for details)
- [x] Documentation regenerated by running `make docs`

### CODE REVIEW

**Comment by bendikp** [comment]
When you have time, @sagikazarmark, it would be nice the get a review on this PR.

**Comment by bendikp** [comment]
When you have time, @sagikazarmark, it would be nice the get a review on this PR.

**Comment by bendikp** [comment]
@nabokihms This PR is now rebased, when you have time, it would be nice to get a review on this PR.

**Review by nabokihms — APPROVED** [review]

**Comment by nabokihms** [comment]
@bendikp sorry for the long delay, nicely done!

**Pull request merged**
